import React, { useState } from 'react';
import { Presentation, GitFork, Building2, Sparkles, Layers } from 'lucide-react';

interface Slide {
  slide: number;
  title: string;
  bullets: string[];
}

interface MindmapNode {
  name: string;
  children?: MindmapNode[];
}

interface SlidesMindmapViewerProps {
  provider: string;
  differences: any[];
}

export const SlidesMindmapViewer: React.FC<SlidesMindmapViewerProps> = ({
  provider,
  differences,
}) => {
  const [industryPreset, setIndustryPreset] = useState<'ship' | 'insurance' | 'regulation'>('ship');
  const [activeSlide, setActiveSlide] = useState<number>(1);
  const [isLoading, setIsLoading] = useState<boolean>(false);

  const [slides, setSlides] = useState<Slide[]>([
    { slide: 1, title: 'AI 船舶技術文件差異 Agent - Demo Day 簡報', bullets: ['S1000D 100% 精準頁碼對照', '工安數值高紅自動警示'] },
    { slide: 2, title: '核心變更與風險指標', bullets: ['冷卻水出口限制由 85°C 降為 80°C (High Risk)', '循環泵浦保養頻率由每月改為每週'] },
    { slide: 3, title: '設備與維修 SOP 影響評估', bullets: ['更新耐熱密封件料號 CP-120', '巡防艦 A/B 型船全適用'] },
    { slide: 4, title: '第一線工程師行動清單與審查簽核', bullets: ['提供逐項 Approve/Disapprove 點擊簽核', '權責 Audit Trail 全程紀錄'] },
    { slide: 5, title: '勝過 NotebookLM 之價值主張', bullets: ['專利 S1000D 原文頁碼雙欄對照', '自訂 DOCX / PDF 審查報告匯出'] },
  ]);

  const [mindmap, setMindmap] = useState<MindmapNode>({
    name: '技術文件改版總覽',
    children: [
      { name: '高風險工安條文', children: [{ name: '出口溫度 85°C ➔ 80°C' }] },
      { name: '設備保養頻率', children: [{ name: '每月 ➔ 每週保養' }] },
      { name: '零件料號更新', children: [{ name: 'CP-100 ➔ CP-120' }] },
    ],
  });

  const handleGenerateAI = async () => {
    setIsLoading(true);
    try {
      const res = await fetch('/api/slides-mindmap', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ differences, provider }),
      });
      if (res.ok) {
        const data = await res.json();
        if (data.presentation_slides) setSlides(data.presentation_slides);
        if (data.mindmap_tree) setMindmap(data.mindmap_tree);
      }
    } catch (err) {
      console.error('Failed to generate slides', err);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="space-y-6">
      
      {/* Industry & Scenario Presets Selector */}
      <div className="bg-slate-900 border border-slate-800 rounded-2xl p-5 flex flex-wrap items-center justify-between gap-4">
        <div className="flex items-center gap-3">
          <div className="p-2.5 bg-indigo-500/10 text-indigo-400 rounded-xl border border-indigo-500/20">
            <Building2 className="w-5 h-5" />
          </div>
          <div>
            <h3 className="text-sm font-bold text-slate-100">
              🏢 跨產業 (產險 / 法規 / 船舶) 預設情境切換器
            </h3>
            <p className="text-xs text-slate-400">
              展示 Agent 在不同高合規領域 (年度法規與保險條款) 之擴充性
            </p>
          </div>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={() => setIndustryPreset('ship')}
            className={`px-3 py-1.5 rounded-xl text-xs font-semibold transition-all ${
              industryPreset === 'ship'
                ? 'bg-teal-600 text-white shadow-lg'
                : 'bg-slate-800 text-slate-400 hover:text-slate-200'
            }`}
          >
            🚢 船舶技術手冊 (Demo 預設)
          </button>
          <button
            onClick={() => setIndustryPreset('insurance')}
            className={`px-3 py-1.5 rounded-xl text-xs font-semibold transition-all ${
              industryPreset === 'insurance'
                ? 'bg-amber-600 text-white shadow-lg'
                : 'bg-slate-800 text-slate-400 hover:text-slate-200'
            }`}
          >
            📑 海事產險保條比對
          </button>
          <button
            onClick={() => setIndustryPreset('regulation')}
            className={`px-3 py-1.5 rounded-xl text-xs font-semibold transition-all ${
              industryPreset === 'regulation'
                ? 'bg-purple-600 text-white shadow-lg'
                : 'bg-slate-800 text-slate-400 hover:text-slate-200'
            }`}
          >
            ⚖️ 鋼船規範 2025 vs 2026
          </button>
        </div>
      </div>

      {/* Slide Deck & Mindmap Dual Panel */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        
        {/* Left: 5-Slide Presentation Deck */}
        <div className="bg-slate-900 border border-slate-800 rounded-2xl p-5 space-y-4">
          <div className="flex items-center justify-between border-b border-slate-800 pb-3">
            <div className="flex items-center gap-2">
              <Presentation className="w-5 h-5 text-teal-400" />
              <h3 className="text-sm font-bold text-slate-200">
                Demo Day 5 頁簡報大綱 (Generated by AWS Bedrock / ChatGPT)
              </h3>
            </div>
            <button
              onClick={handleGenerateAI}
              disabled={isLoading}
              className="px-3 py-1 bg-teal-600/20 text-teal-300 border border-teal-500/30 hover:bg-teal-600 hover:text-white rounded-lg text-xs font-bold transition-all flex items-center gap-1"
            >
              <Sparkles className="w-3.5 h-3.5" />
              {isLoading ? '生成中...' : '重新生成'}
            </button>
          </div>

          {/* Active Slide Display */}
          {slides.length > 0 && (
            <div className="bg-slate-800/80 border border-slate-700/80 rounded-xl p-5 min-h-[220px] flex flex-col justify-between space-y-3">
              <div>
                <div className="text-[10px] font-bold text-teal-400 uppercase tracking-wider mb-1">
                  SLIDE {slides[activeSlide - 1]?.slide || activeSlide} OF 5
                </div>
                <h4 className="text-base font-bold text-slate-100">
                  {slides[activeSlide - 1]?.title}
                </h4>
                <ul className="mt-3 space-y-2 text-xs text-slate-300">
                  {slides[activeSlide - 1]?.bullets.map((b, idx) => (
                    <li key={idx} className="flex items-start gap-2">
                      <span className="text-teal-400 font-bold">•</span>
                      <span>{b}</span>
                    </li>
                  ))}
                </ul>
              </div>

              {/* Navigation dots */}
              <div className="flex items-center justify-center gap-2 pt-2 border-t border-slate-700/60">
                {[1, 2, 3, 4, 5].map((num) => (
                  <button
                    key={num}
                    onClick={() => setActiveSlide(num)}
                    className={`w-7 h-7 rounded-lg text-xs font-bold transition-all ${
                      activeSlide === num
                        ? 'bg-teal-600 text-white'
                        : 'bg-slate-700 text-slate-400 hover:text-slate-200'
                    }`}
                  >
                    {num}
                  </button>
                ))}
              </div>
            </div>
          )}
        </div>

        {/* Right: Mindmap Tree View */}
        <div className="bg-slate-900 border border-slate-800 rounded-2xl p-5 space-y-4">
          <div className="flex items-center justify-between border-b border-slate-800 pb-3">
            <div className="flex items-center gap-2">
              <GitFork className="w-5 h-5 text-cyan-400" />
              <h3 className="text-sm font-bold text-slate-200">
                變更心智圖樹狀圖 (Mindmap Tree)
              </h3>
            </div>
          </div>

          <div className="bg-slate-800/60 border border-slate-700/80 rounded-xl p-5 min-h-[220px] text-xs space-y-3">
            <div className="font-bold text-slate-100 text-sm flex items-center gap-2">
              <Layers className="w-4 h-4 text-cyan-400" />
              {mindmap.name}
            </div>

            <div className="pl-4 space-y-2 border-l border-slate-700">
              {mindmap.children?.map((child, idx) => (
                <div key={idx} className="space-y-1">
                  <div className="font-semibold text-slate-200">{child.name}</div>
                  <div className="pl-4 space-y-1 border-l border-slate-700/60">
                    {child.children?.map((leaf, lIdx) => (
                      <div key={lIdx} className="text-slate-400 text-[11px]">
                        • {leaf.name}
                      </div>
                    ))}
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>

      </div>
    </div>
  );
};
